version: '3.9'

services:
  petstore-demo-server:
    build:
      dockerfile: dev.Dockerfile
      context: .
    command: ["run"]
    networks:
      - petstore-demo-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  petstore-demo-database:
    container_name: petstore-demo-database
    image: mysql:8
    restart: always
    networks:
      - petstore-demo-network
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - petstore-demo-database-data:/var/lib/mysql
    env_file:
      - .env

  petstore-demo-jaeger:
    container_name: petstore-demo-jaeger
    image: jaegertracing/all-in-one
    networks:
      - petstore-demo-network
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  petstore-demo-database-data:
    driver: local

networks:
  petstore-demo-network:
    driver: bridge
