// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Owner struct {
	ID   int32          `json:"id"`
	Name string         `json:"name"`
	Bio  sql.NullString `json:"bio"`
}

type Pet struct {
	ID      int32         `json:"id"`
	Name    string        `json:"name"`
	Type    string        `json:"type"`
	OwnerID sql.NullInt32 `json:"owner_id"`
}
