app:
  name: http-app
  version: 0.1.0
modules:
  core:
    server:
      address: ":8081"
      dashboard:
        enabled: true
        overview:
          app_env: true
          app_debug: true
          app_version: true
          log_level: true
          log_output: true
          trace_sampler: true
          trace_processor: true
      metrics:
        expose: true
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
      healthcheck:
        startup:
          expose: true
        readiness:
          expose: true
        liveness:
          expose: true
      debug:
        config:
          expose: true
        pprof:
          expose: true
        routes:
          expose: true
        stats:
          expose: true
        build:
          expose: true
        modules:
          expose: true
  http:
    server:
      address: ":8080"
      errors:
        obfuscate: true
        stack: false
      trace:
        enabled: true
      metrics:
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
  database:
    #driver: sqlite
    #dsn: "file:database.sqlite"
    driver: mysql
    dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
    migrations: db/migrations
  log:
    level: info
    output: stdout
  trace:
    processor:
      type: otlp-grpc
      options:
        host: ${OTLP_COLLECTOR_HOST}:${OTLP_COLLECTOR_PORT}
